services:
  # API Gateway
  api-gateway:
    image: ${REGISTRY}/gha-api-gateway:${IMAGE_VERSION}
    container_name: gha-api-gateway
    ports:
      - "${API_GATEWAY_HOST_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      orchestrator:
        condition: service_healthy
    networks:
      - gha-network
    restart: unless-stopped

  # Orquestador
  orchestrator:
    image: ${REGISTRY}/gha-orchestrator:${IMAGE_VERSION}
    container_name: gha-orchestrator
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gha-network
    restart: unless-stopped

networks:
  gha-network:
    driver: bridge
